{% set version = "1.0.1" %}

package:
  name: scikit-learn
  version: {{ version }}

source:
  url: https://github.com/scikit-learn/scikit-learn/archive/{{ version }}.tar.gz
  sha256: 1b4d6b023baaf20b4d1b70ed67033182089c03995dc7ae0e803645fa9ed024f9
  patches:
   - patches/0001-ignore-errors-when-tearing-down-modules.patch

build:
  number: 2
  skip: true  # [py<37]
  script:
    - rm $PREFIX/include/cblas.h  # [not win]
    - del /f %LIBRARY_INC%\cblas.h  # [win]
    # build the C files in parallel. This helps beat the
    # time limit consistently on drone.io
    - {{ PYTHON }} setup.py build_ext -j{{ CPU_COUNT }}
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - scipy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
  host:
    - python
    - pip
    - cython >=0.28.5
    - libcblas
    - numpy
    - scipy >=0.17.0
    - joblib >=0.11
    - threadpoolctl
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - joblib >=0.11
    - threadpoolctl

{% set tests_to_skip = "_not_a_real_test" %}
{% set extra_pytest_args = "" %}
# https://github.com/scikit-learn/scikit-learn/issues/20335
{% set tests_to_skip = tests_to_skip + " or test_loadings_converges" %}
# Numerically unstable test numerical difference in test
{% set tests_to_skip = tests_to_skip + " or test_mlp_regressor_dtypes_casting" %}         # [ppc64le]

test:
  requires:
    - pytest >=3.3.0
    - cython >=0.28.5
    - pytest-xdist
    - pytest-timeout
  imports:
    - sklearn
  commands:
    - pytest --pyargs sklearn -k "not ({{ tests_to_skip }})" -nauto --timeout=1200 --durations=50  # [not ppc64le]

about:
  home: http://scikit-learn.org/
  license: BSD-3-Clause
  license_file: COPYING
  summary: A set of python modules for machine learning and data mining

extra:
  recipe-maintainers:
    - amueller
    - astaric
    - jakirkham
    - ogrisel
    - ocefpaf
    - lesteve
    - jnothman
    - rth
    - adrinjalali
    - glemaitre
    - jeremiedbb
